version: '3.3'
services:
  postgres:
    image: postgres:10.5
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha43
    depends_on:
    - "postgres"
    restart: always
    environment:
      # database url to connect
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      # enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: hAsuRa_plaY!gr0uNd
      HASURA_GRAPHQL_JWT_SECRET: "{\"type\":\"HS256\", \"key\": \"5c90a95d02b3ee7ae376166e8e5e9893\"}"
    ports:
      - "80:8080"
    command:
    - graphql-engine 
    - serve
  # caddy:
  #   image: abiosoft/caddy:0.11.0
  #   depends_on:
  #   - "graphql-engine"
  #   restart: always
  #   ports:
  #   - "80:80"
  #   - "443:443"
  #   volumes:
    # - ./Caddyfile:/etc/Caddyfile
    # - caddy_certs:/root/.caddy
volumes:
  db_data:
  # caddy_certs: